export const PLAN_COPY = {
  headerLabel: 'This week',
  fallbackTitle: 'Let’s start simple.',
  fallbackBody: 'Start with one task. Domains can adjust around it.',
  promptTitle: 'What are a few things you know you’ll spend time on this week?',
  promptNote: 'Tasks first. Domains can be adjusted anytime.',
  taskPlaceholder: 'e.g. meetings, gym, reading, coursework',
  hoursHelper: 'A rough guess is enough.',
  hoursLabel: 'Rough time (hours)',
  hoursLabelShort: 'Hours',
  taskLabel: 'Task',
  addTask: 'Add task',
  quickTasksTitle: 'Common tasks (optional)',
  quickTasksNote: 'You can add these with one tap, or skip them.',
  quickTaskMaintenance: 'Maintenance',
  quickTaskSleep: 'Sleep',
  quickTaskCommitments: 'Commitments',
  planningLeftLabel: 'Planning time left',
  planningLeftNote: 'Based on your baseline settings and this week’s tasks.',
  emptyTaskHint: 'Start with one thing you already know you’ll do.',
  plotHint: 'The shape will settle as you add a few tasks.',
  plotNote: 'It’s a sketch of your week, not a score.',
  summaryTitle: 'Domains are just containers for this week.',
  summaryNote: 'Tasks give the plot its shape.',
  domainHint: 'Domains are just containers for this week.',
  tasksShapeHint: 'Tasks give the plot its shape.',
  saveDraft: 'Save draft',
  completePlanning: 'Complete planning',
  saveDraftNote: 'This is just a plan. You can change it as the week unfolds.',
  largestDomainLabel: 'This is a distribution of your time over the week.',
  largestDomainNote: 'It reflects time planned, not importance.',
  pickDomain: 'Pick a domain to start.',
  renameHint: 'You can rename domains as you go.',
  addDomain: 'Add domain',
  maxDomains: 'Max 7 domains for a week.',
  taskListTitle: 'Your tasks (rough draft)',
  taskListNote: 'Click a domain tag to adjust it.',
  taskPanelTitle: 'Domain tasks',
  taskPanelEmpty: 'No tasks here yet.',
  taskPanelHint: 'Select a domain to see its tasks.',
  saveStatus: 'Draft saved.',
  createDomain: 'Create new domain',
  domainPickerLabel: 'Assign domain',
  domainOtherPlaceholder: 'New domain name',
  domainLimitNote: 'Max 7 domains for a week.',
  domainAssignHelper: 'Domains help group your time. You can change this anytime.',
  hoursAria: 'Planned hours',
  plotHeader: 'What this week looks like so far',
  plotSubtext: 'This is a soft sketch, not a score.',
};
